### ISSUE TITLE
Project Details view cannot be opened (missing UUID in URL -> Error 500)

### ISSUE THREAD

**Issue by rkg-mm** [DependencyTrack/frontend#706]
### Current Behavior

I am unable to open the "View Details" window of some of our projects. Others work fine. The problematic projects try to request 
https://dtrack-api.mm-software.com/api/v1/project/undefined

Somehow the projects UUID is not available when creating the URL, resulting in an "undefined" instead of the UUID. This causes a ERROR 500 on the server due to the missing ID. (Shouldn't this be a 400?)

### Steps to Reproduce

1. Open a project (it only happens on some projects, no idea why on these and not on others)
2. Click "View Details"
3. See the error

### Expected Behavior

No error

### Dependency-Track Frontend Version

4.10.0

### Browser

Mozilla Firefox

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
I've seen this happen before when browser caches were stale. Is this reproducible with another browser, in private mode, or after clearing caches?

**Comment by nscuro** [comment]
@rkg-mm Is everything else on the project page working normal? Any chance you can inspect the response to the `/project` request being made, when initially opening the project page (not the details)?

**Comment by rkg-mm** [comment]
everything else works as expected.

Response from /api/v1/project/25abbaf9-a777-420b-99a6-77a1fb6e8dc7
![image](https://github.com/DependencyTrack/frontend/assets/12029804/1c3ad950-4688-4abb-a737-0392c7873433)

**Comment by rkg-mm** [comment]
I tried to debug into it in our production instance, so the URL is being wrongly created here, because parent.uuid is not defined:
![image](https://github.com/DependencyTrack/frontend/assets/12029804/f26e4d12-ee04-4b1a-be77-2776d4b9281f)

**Comment by rkg-mm** [comment]
@nscuro can you try to prioritize a fix for this for next version? I found by chance 20-30 projects that are affected by this now :(

**Comment by nscuro** [comment]
I think this is already fixed in v4.12, although more or less by accident: https://github.com/DependencyTrack/dependency-track/issues/3883#issuecomment-2218226036

**Comment by rkg-mm** [comment]
I don't know what steps cause this actually. Its reproducable on the same projects. Once happened on a project it happens for months (I know of 4 projects since January which still don't work), also rebooting and installing updates remains the same behavior. However, most other projects work fine.
I can try again with 4.12 and these 4 projects, they are planned to be deleted so I can just keep them in this state until then. 
Other projects I fixed via PATCH call, that worked.

**Comment by nscuro** [comment]
Is there any other context you can share about this? Like how deep is the nesting of the parent-child relationships for these projects?

I think we can at the very least make the UI *not break* when the parent couldn't be fetched, but of course this is only a stop-gap and doesn't solve the underlying problem.

**Comment by rkg-mm** [comment]
Nothing that is consistent.

The 4 projects are on 3rd level
X -> Y -> Z, with Z being problematic, all with the same parent.

But the projects I struggled with yesterday were on 2nd level (Y), also same parent, but there were also other projects on same level below this parent, which worked fine.

I could not find any consistency.

**Comment by nscuro** [comment]
Through creating a script that creates numerous child projects, fetches them again, and then checks whether the response contains data about the parent, I was able to reproduce this.

What's odd is that `Project#parent` **is** loaded. It's just empty, for whatever reason. Even using the ORM's internal APIs to inspect whether a field is loaded tells me the field is loaded. What's even more odd, is that even `Project#children[]#parent` is loaded, and fully populated in the response. So it's not an issue with the fetch depth either.

It seems that detaching the `project` prior to returning it as `Response` fixes the issue, however load testing the endpoint before and after this change gives me absolutely horrendous numbers.

Before:
```
Latency distribution:
  10% in 0.0424 secs
  25% in 0.0616 secs
  50% in 0.1976 secs
  75% in 0.2816 secs
  90% in 0.3226 secs
  95% in 0.3587 secs
  99% in 0.3825 secs
```

After:
```
Latency distribution:
  10% in 2.9727 secs
  25% in 3.0208 secs
  50% in 3.0722 secs
  75% in 3.1387 secs
  90% in 3.2269 secs
  95% in 3.3220 secs
  99% in 3.3933 secs
```

Bear in mind I'm testing on a local machine, with H2 database. It will be much worse in production systems. 

At this point I'm suspecting this to be a bug in the ORM. We have a solution that fixes the issue, but introduces a very bad performance regression that will make the UI even more sluggish.
